variable "allow_ports" {}
variable "general_tags" {}
variable "vpc_1_instance_tenancy" {}
variable "vpc_1_cidr_block" {}
variable "public_subnet_1_cidr_block" {}
variable "public_subnet_1_availability_zone" {}
variable "public_subnet_1_map_public_ip_on_launch" {}
variable "private_subnet_1_cidr_block" {}
variable "private_subnet_1_availability_zone" {}
variable "eip_vpc" {}
variable "public_subnet_2_cidr_block" {}
variable "public_subnet_2_availability_zone" {}
variable "private_subnet_2_cidr_block" {}
variable "private_subnet_2_availability_zone" {}