variable "instance_ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "general_tags" {}
variable "sg_public_1_id" {}
variable "sg_private_1_id" {}
variable "sg_public_2_id" {}
variable "sg_private_2_id" {}
variable "vpc_1_public_subnet" {}
variable "vpc_1_private_subnet" {}
variable "vpc_2_public_subnet" {}
variable "vpc_2_private_subnet" {}
variable "aws_instance_associate_public_address" {}